
server:
  port: 5010
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

logging:
  level:
    com.example: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

spring:
  rabbitmq:
    host: 'localhost'
    password: guest
    port: 5672
    username: guest
  jpa:
    open-in-view: false

rabbit:
  config:
    exchange:
      shopping: "ex_compras"
      sales: "ex_vendas"
    routing:
      shopping: "router_compras"
      sales: "router_vendas"
    queue:
      shopping: "queue_compras"
      sales: "queue_vendas"
      audit: "queue_auditoria"

app:
  gc-two:
    url: http://localhost:5003
    name: gc-two